version: "3.8"

services:
  web:
    build: .
    volumes:
      - ../:/workspace:cached
      - maven-repo:/root/.m2
      - vscode-extension-java:/root/.vscode-server/extensions
    environment:
      APPLICATION_PORT: 8080
      MONGODB_URI: "mongodb://root:root@db:27017/admin"
    ports:
      - "8080:8080"
    networks:
      - demo-network
    command: /bin/sh -c "while sleep 1000; do :; done"
    
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
    - mongodb_data:/data/db
    - mongodb_config:/data/configdb
    networks:
      - demo-network

volumes:
  maven-repo:
    external: true
  mongodb_data:
    external: true
  mongodb_config:
    external: true
  vscode-extension-java:
    external: true

networks:
  demo-network:
    external: 
      name: demo-network

